### ISSUE TITLE
Rename `mask-directive` module to `jst-mask` to use default names

### ISSUE THREAD

**Issue by felipebonezi** [justapagamentos/justa-angular-library#6]
We need to make our library to use default names using `JST` as preffix.

**Comment by raisiqueira** [comment]
Suggestion: Move all `NG Packages` to this repository, in this repo we have the `jst-pagination` and `mask-directive` packges, the `jst-validators` are in other repository.

@felipebonezi @matheusnascgomes @mguilhermetavares @lavesan
